### ISSUE TITLE
Release 2.8

### ISSUE THREAD

**Issue by benbovy** [fastscape-lem/fastscapelib-fortran#21]
- [x] update release notes in the docs!

Changes:

- [x] refactor stream power law implementation (decouple from flow routing) #23
- [x] rename ``Union`` internal subroutine (could cause name conflicts when building the library with f2py) #22 

New features:

- [x] new routines for computing curvature and slope #15   
- [x] new component for marine sediment transport and deposition #20

Bug fixes and improvements:

- [x] fixed VTK files export on Windows #7  
- [x] improved efficiency of stream power law erosion and flexure #8
- [x] fixed bug in lake filling algorithm #12 
- [x] fixed bug in ADI implementation of diffusion #17 
- [x] fixed bug in ``Strati`` subroutine #18
